name: Auto-update README with Certificates

on:
  push:
    paths:
      - '*.pdf'
      - '.github/workflows/update-readme.yml'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate updated README
        run: |
          echo "# 🎓 Professional Certifications" > README.md
          echo "" >> README.md
          echo "List of all certificates stored in this repository:" >> README.md
          echo "" >> README.md
          for file in *.pdf; do
            echo "- [${file%.*}](https://github.com/${{ github.repository }}/raw/main/$file)" >> README.md
          done
          echo "" >> README.md
          echo "---" >> README.md
          echo "_Automatically updated on push._" >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with new certificates" || echo "No changes to commit"
          git push
